context:
  name: numba-cuda
  sdist_name: numba_cuda
  version: "0.15.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ sdist_name }}-${{ version }}.tar.gz
  sha256: eb0b0621b93fc4ed36e8cdac68b9ad1d408e249c2e4d3e93fb7c37ffe0580448

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numba >=0.59.1
    - cuda-version >=11.2
    - cuda-bindings  # Includes nvrtc, nvvm, libdevice
    - cuda-cudart-dev  # Includes cudadevrt

tests:
  - python:
      imports:
        - numba_cuda
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/NVIDIA/numba-cuda
  summary: 'A CUDA target for Numba'
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  documentation: https://nvidia.github.io/numba-cuda
  repository: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - bdice
    - gmarkall
    - vyasr
    - kkraus14
