context:
  name: numba-cuda
  sdist_name: numba_cuda
  version: "0.0.17.1"
  python_min: "3.9"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ sdist_name }}-${{ version }}.tar.gz
  sha256: 6963e0f5ea7838700eb1ff7017070e2b4a31791fd1072cd8d514e85609786499

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numba >=0.59.1

tests:
  - requirements:
      run:
        - python ${{ python_min }}
        - pip
    script:
      - python -m pip check
      - python -c "import numba_cuda"

about:
  homepage: https://github.com/NVIDIA/numba-cuda
  summary: 'A CUDA target for Numba'
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  documentation: https://nvidia.github.io/numba-cuda
  repository: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - bdice
    - gmarkall
    - vyasr
