context:
  name: numba-cuda
  sdist_name: numba_cuda
  version: "0.19.2rc0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ sdist_name }}-${{ version }}.tar.gz
  sha256: 92dc1f2a1df0adbf7a811fe71acb5092cb96f0ee0e7d192c5f1fa14f315b499a

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numba >=0.60.0
    - cuda-bindings >=12.9.1
    - cuda-core ~=0.3  # >=0.3,<0.4
    - cuda-cudart-dev
    - cuda-version >=12 

tests:
  - python:
      imports:
        - numba_cuda
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/NVIDIA/numba-cuda
  summary: 'A CUDA target for Numba'
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  documentation: https://nvidia.github.io/numba-cuda
  repository: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - leofang
    - bdice
    - gmarkall
    - vyasr
    - kkraus14
