context:
  name: numba-cuda
  sdist_name: numba_cuda
  version: "0.16.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ sdist_name }}-${{ version }}.tar.gz
  sha256: bd5214de68cb51426dcf88ee477823853c7bf43c0b8266fac7616f9009a83a2b

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numba >=0.59.1
    - cuda-bindings  # Includes nvrtc, nvvm, libdevice for CUDA 12, cudatoolkit for CUDA 11
    - cuda-core ~=0.3  # >=0.3,<0.4 
    - if: cuda_version == "12+"
      then:
        - cuda-cudart-dev
        - cuda-version >=12
    - if: cuda_version == "11"
      then:
        - cuda-version >=11.2,<12

tests:
  - python:
      imports:
        - numba_cuda
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/NVIDIA/numba-cuda
  summary: 'A CUDA target for Numba'
  description: |
    A Numba target for compiling Python code to excute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  documentation: https://nvidia.github.io/numba-cuda
  repository: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - leofang
    - bdice
    - gmarkall
    - vyasr
    - kkraus14
