context:
  name: numba-cuda
  sdist_name: numba_cuda
  version: 0.25.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/numba-cuda/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b32406f5b631f5870d00f79b50d96ffc3b683c71283b825bca36889cc6336630

build:
  script: python -m pip install . -vv
  number: 0
  skip: [osx or ppc64le]

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy >=2.1.0
  run:
    - python
    - numba >=0.60.0
    - numpy >=1.22
    - cuda-bindings >=12.9.1,<14.0.0
    - cuda-core >=0.3.2,<1.0.0
    - cuda-cudart-dev
    - cuda-version >=12
    - cuda-nvcc-impl
    - packaging

tests:
  - python:
      imports:
        - numba_cuda
      pip_check: true

about:
  homepage: https://github.com/NVIDIA/numba-cuda
  summary: A CUDA target for Numba
  description: |
    A Numba target for compiling Python code to execute on CUDA GPUs.
  license: BSD-2-Clause
  license_file: LICENSE
  documentation: https://nvidia.github.io/numba-cuda
  repository: https://github.com/NVIDIA/numba-cuda

extra:
  recipe-maintainers:
    - brandon-b-miller
    - rparolin
    - conda-forge/cuda-python
    - leofang
    - bdice
    - gmarkall
    - vyasr
    - kkraus14
