bot:
  inspection: update-grayskull
build_platform:
  linux_aarch64: linux_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
linter:
  skip:
  - lint_noarch_selectors
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
